// AUTO DISH LIVE
const DISH_APPROVED_REQUIRED_KEY = 'dishApprovalRequired';
// MINIMUM ORDER NUMBER
const MINIMUM_ORDER_AMOUNT_KEY = 'minimumOrderAmount';
// MAXIMUM ORDER AMOUNT
const MAXIMUM_ORDER_AMOUNT_KEY = 'maximumOrderAmount';
// ORDER COMMISSION
const ORDER_COMMISSION_PERCENTAGE_KEY = 'orderCommissionPercentage';
// DEFAULT OPENING HOUR
const DEFAULT_OPENING_HOUR_KEY = 'defaultOpeningHours';
// DEFAULT DELIVERY HOUR
const DEFAULT_DELIVERY_HOUR_KEY = 'defaultDeliveryHours';

module.exports = {
  DISH_APPROVED_REQUIRED_KEY,
  MINIMUM_ORDER_AMOUNT_KEY,
  MAXIMUM_ORDER_AMOUNT_KEY,
  ORDER_COMMISSION_PERCENTAGE_KEY,
  DEFAULT_DELIVERY_HOUR_KEY,
  DEFAULT_OPENING_HOUR_KEY,
};
